version: '3'

services:
  reverse-proxy:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build:
      context: ./services/front
    container_name: "app"
    volumes:
      - ./services/front:/workdir
    ports:
      - '3000:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"

  api:
    build:
      context: ./services/back
    container_name: "api"
    volumes:
      - ./services/back:/workdir
    ports:
      - '4000:4000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
    secrets:
      - git_ssh_key

secrets:
  git_ssh_key:
    file: ~/.ssh/kikimeter/id_git
