import React from "react"

import Typography from '@mui/material/Typography'

const LogodenBiniou = () => {
  return (
    <React.Fragment>
      <Typography paragraph>
        Logoden biniou degemer mat an penn ar bed kemmañ, gentel Montroulez dec’h seizhvet Plelann-Veur gloan e birviñ Kemper, poan dale foenn dilhad tavarnour kenwerzh petra. Kalon buoc’h hi goude poazh sec’hañ Egineg gontell Aradon estreget  penaos alies o klouar, danvez drezomp loa start Montroulez deñvalijenn envel askorn wouel hennont ker. Divskouarn kann sukr kement follenn merc’her digant leskiñ gwalc’hiñ paour dad moan dit per, derc’hent oas vuzell davet  na bezh pod Atlantel niver muzell señin. Planken prad tad kann Gwikourvest kelc’h bluenn c’hoari skrijañ, enep garmiñ ankouna’haat hag dud formaj egisto kenañ koulskoude, davañjer droug gwele gwiskañ muiañ kilañ vihan. Arvor lonkañ goulenn gentel ha lamp c\hlas saveteiñ e, Douarnenez boan amzer Egineg c’hoar chase tra bugale dro, mezher ha Plouha kraou hegarat poazhañ anezho. Speredekañ ijinañ start eur warlene nadoz aer unan lakaat, kraou d’a evañ ur kaier gwec’h gourc’hemenn al Pont’n-Abad, e beajour draonienn brudet Krouer distagañ morzhol. C’hoazh roud evañ dorgenn Naoned c’hewz naet onest Plouared, kant gourc’hemenn hervez da feiz lizher reas diwezhañ patatez, gwelloc’h koll sal Ar Vouster daouzek kennebeut skevent. Park werenn drezout gousperoù eured gouzoug tasenn gouiziek out, garm Rosko servijañ holl distagañ fentigelloù drezañ vaneg Gwened, ac'hanomp Baen-Veur vourc’h goap o skolaer eizh. Warnon dro enep wec’h prenestr gwinizh egiston Skrigneg soavon, dra fall bloavezh mui stag tri er naon amann, degas penaos Mor c’houmoul bara Plourin-Montroulez levr. Trugarez galv terriñ nizez kreisteiz gasoni fur c’hemener c’heuz, paotrig ouzhin maen mezher fellout paotr krouiñ evit ar, war ruilhañ vuzell outi egisto pennad Nazer.
      </Typography>
      <Typography paragraph>
      Bep lenn Abbarez kav aes sukr ouzhpenn c’hi sul, dirak  mezher mintin rak oentr fuzuilh heñvel hegarat gwer, Brieg godell e Plouneour-Menez c’hoant skevent evel . Gavr ugent kreñv Pabu labous kreskiñ re grizilh outo, c’haier banne arrebeuri c’hoant ganin ilin kozh da paotrig, sac’h sal toullañ seizh pignat miliner ur. Ha blev melezour warnout spontus chokolad formaj gwiskañ delioù, an nec’hin Mellag derc’hent karrezek c’hwi an gounit gouzout, leur lizher kilhog a goleiñ lous eno. Warnañ, degas doare ha an brodañ c’har gousperoù brudet, itron korn prenestr gwerzhañ beajiñ skignañ neud gaer ganet, moged Naoned egistañ kezeg pegeit Pederneg drezi. Vloaz arvar paouez doñv kalz Brest muioc’h talvezout fri gwele kilañ bloaz distagañ esaeañ, barv dirak planken harzhal kement c’hartoñs glac’har kribañ kein aketus homañ. Ael stagañ Roazhon bann tabut Pederneg diwezhat davarn druez, spi den gouiziek wastell onest Montroulez ha nadoz warlene, houlenn blijadur distagañ start met poazh evidout. Ziskouez loer n’eus hep  estreget  gouel blev ennañ trec’h, pleg e loar Montroulez paour yezh amañ lestr ac’hano, ennomp evitañ me c’hotoñs kraou biz Muzilheg. Tremen ar gwiskamant goañv echu c’heuz aour paour warnout, dezhañ loer lous rumm nizez skubañ here ha traezh, trouz diskiant an soavon emaout hepken c’harrez. Saveteiñ mezheven medisin hag da tann Briad levr ganimp, ganeomp, kenavo matezh lizher nizez Skos pepr war panevet  a, lous war puñs pesketaer hejañ c’hleuz dimeziñ. Da kenavo Melwenn flamm planken Roazhon kêr Abbarez traonienn, dirak  c’houlz paotrig Eusa gwalenn da kerkent komz montr, abardaez fazi tregont trec’h zo tavañjer brezhoneg.
      </Typography>
    </React.Fragment>
  )
}

export default LogodenBiniou
